# Generated by Django 5.1.7 on 2025-05-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employeelist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address_cd",
            field=models.IntegerField(null=True),
        ),
    ]
