# Generated by Django 5.1.7 on 2025-05-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employeelist", "0002_employee_address_cd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="address_cd",
        ),
    ]
